In [4]:
import pandas as pd
pd.__version__

'2.3.0'

In [6]:
seri = pd.Series([100,200,300,400])
print(seri)

0    100
1    200
2    300
3    400
dtype: int64

In [10]:
nufus = pd.Series([585000,631000,15000000,1000000,4000000], index = ['Zonguldak', 'Sivas','İstanbul','Balıkesir','İzmir'])
print(nufus["Zonguldak"])
print(nufus.sum())

585000
21216000

In [11]:
# Ürün, fiyat 
urunler = pd.DataFrame({
    "urun": ["Laptop", "Telefon", "Tablet", "Klavye", "Mouse"],
    "fiyat": [25000, 18000, 12000, 1500, 800],
    "stok": [10, 15, 8, 25, 30]
})

print(urunler)

      urun  fiyat  stok
0   Laptop  25000    10
1  Telefon  18000    15
2   Tablet  12000     8
3   Klavye   1500    25
4    Mouse    800    30

In [22]:
# Sınıf arkadaşları
arkadaslar = pd.DataFrame({
    "isim": ["Ahmet", "Ayşe", "Mehmet", "Zeynep", "Ali"],
    "yas": [22, 21, 23, 22, 24],
    "bolum": ["VeriBilimi", "Fizik", "kimya", "istatistik", "matematik"]
})

print(arkadaslar)

print(arkadaslar.shape)

     isim  yas       bolum
0   Ahmet   22  VeriBilimi
1    Ayşe   21       Fizik
2  Mehmet   23       kimya
3  Zeynep   22  istatistik
4     Ali   24   matematik
(5, 3)

In [23]:
# csv için
arkadaslar.to_csv("ogrenciler.csv")

In [15]:
ogrenciler = pd.read_csv("ogrenciler.csv")

print(ogrenciler)

   Unnamed: 0    isim  yas       bolum
0           0   Ahmet   22  VeriBilimi
1           1    Ayşe   21       Fizik
2           2  Mehmet   23       kimya
3           3  Zeynep   22  istatistik
4           4     Ali   24   matematik

In [17]:
arkadaslar.head(3)

     isim  yas       bolum
0   Ahmet   22  VeriBilimi
1    Ayşe   21       Fizik
2  Mehmet   23       kimya

In [18]:
arkadaslar.tail(2)

     isim  yas       bolum
3  Zeynep   22  istatistik
4     Ali   24   matematik

In [27]:
arkadaslar.info()
print(arkadaslar.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   isim    5 non-null      object
 1   yas     5 non-null      int64
 2   bolum   5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes
(5, 3)

In [28]:
arkadaslar.describe()

             yas
count   5.000000
mean   22.400000
std     1.140175
min    21.000000
25%    22.000000
50%    22.000000
75%    23.000000
max    24.000000

In [30]:
ogrenciler["isim"]
ogrenciler[["isim", "yas"]]

     isim  yas
0   Ahmet   22
1    Ayşe   21
2  Mehmet   23
3  Zeynep   22
4     Ali   24

In [31]:
ogrenciler.loc[0:2]

   Unnamed: 0    isim  yas       bolum
0           0   Ahmet   22  VeriBilimi
1           1    Ayşe   21       Fizik
2           2  Mehmet   23       kimya

In [32]:
ogrenciler.iloc[1, 1]

'Ayşe'